### ISSUE TITLE
To Discuss: Basic TF instructions?

### ISSUE THREAD

**Issue by tanvi-orcl** [SunnyORCL/Iteam-DR-TF#18]
We're creating this for people who don't know TF well and need help knowing what to change from the resource stack correct?

Should we add some level 0 instructions somewhere explaining resource blocks and high level why we're making changes. Generic notes like
- resource blocks reference each other and induce dependencies
- have multiple providers to reference both primary and standby region
- can create data sources occasionally to pull info from the console.

**Comment by salnguyen** [comment]
I think bullet 2 and 3 are good to provide some context. But I'm also not sure if the assumption is that audiences have some foundation of coding experience so bullet 1 can be something related to best practices for managing resources?

________________________________
