### ISSUE TITLE
Define/prepare required variables  (see example in description)

### ISSUE THREAD

**Issue by tanvi-orcl** [SunnyORCL/Iteam-DR-TF#7]
At the top put:

Required variables from OCI Console
- Primary DB OCID
- Primary VCN OCID
- Primary VCN CIDR

In your code, if you're referencing a variable from another file, put a comment/make it clear
ex:
subnet_id = oci_core_subnet.<RESOURCE NAME>.id         # from Core.tf file

**Comment by aberinnj** [comment]
![image](https://user-images.githubusercontent.com/33266049/110396975-96b58580-8036-11eb-8e5d-4938e07847ef.png)

I put mine under Preparation. Is this ok?
